### PR TITLE
Add x11 fowarding to docker container.

### LINKED ISSUE #31: Add X11 forwarding to docker container

### PR DESCRIPTION
**Pull request by jmblixt3**

### CODE REVIEW

**Comment by jmblixt3** [comment]
@Isopod00 Please test on macOS

**Comment by Isopod00** [comment]
> @Isopod00 Please test on macOS

it did not appear to work :(

**Comment by jmblixt3** [comment]
Tested and works on linux

**Review by Isopod00 — APPROVED** [review]
it works on windows and linux so that's enough for me. we can figure out mac later on if needed.

**Pull request merged**
