### PR TITLE
Startup script change

### PR DESCRIPTION
**Pull request by BergerKing333**
Updated enter_isaac_ros_container script to check if the image already exists before trying to build it from scratch. Running build_image.sh everytime takes substantially longer than checking to see if we need to build it vs just opening the container.

### CODE REVIEW

**Review by Isopod00 — APPROVED** [review]
This looks good to me, but Jonathan knows more about this stuff than I do

**Comment by jmblixt3** [comment]
This won't check for updates automatically, which may be problematic. The build script does

**Review by jmblixt3 — COMMENTED** [review]
See comment

**Comment by BergerKing333** [comment]
the build script doesnt see changes anyways. It finds cached image and builds that instead. you have to manually disable the search for cached image before build_immage works. It could also be that you manually run build_image to update image

**Comment by jmblixt3** [comment]
All good then, just didn't want a degredation

**Pull request merged**
