### PR TITLE
Refactor all of our Swerve Drive code into Tank Drive

### LINKED ISSUE #275: Refactor swerve drive into tank drive
Completed Tasks:
-Refactor the drivetrain and motor_control config files (remove swerve-specific stuff)
-Refactor our driving controls in the main control node (revert back to how we did it on the 2023 robot)
-Refactor read_serial to not read from Absolute Encoders anymore
-Refactor our Arduino sensors.ino sketch to not read from Absolute Encoders anymore
-Remove the instantiated PID controllers for the turning motors in motor_control
-Refactor the drivetrain node from swerve into tank drive
-Refactor all usages of the drive ROS service
-Refactor our simulated robot to fix the angle of all 4 wheels and drive like tank drive instead of swerve by modifying src/robot_description/models/master_ASM/urdf/master_ASM.urdf.xacro and setting the swerve joints to fixed
-Refactor our Nav2 config file for tank drive (don't allow horizontal movement, look at an old version of the config file). Look at [this](https://github.com/GOFIRST-Robotics/Lunabotics/commit/77b61f9e2d913ebc39c312b4ca8b06b3c6b7c8a1) commit to see how we changed it from the default for swerve (ignore the autoformatting / whitespace changes)
-Build & run the motor_control_node to make sure it doesn't crash (everything else will be tested by the other testing steps)
-Test Nav2 goals while echoing the cmd_vel topic to ensure that Nav2 is not commanding any horizontal velocity
-Test our changes in the Gazebo simulation to make sure tank driving is working! We should be able to drive the simulated robot
-Test & Improve Nav2 path following in our Gazebo simulation with "ros2 launch isaac_ros_launch gazebo_launch.py"

### PR DESCRIPTION
**Pull request by Isopod00**
Our robot last year utilized Swerve Drive for its drivetrain style, but this year we plan to use Tank Drive instead as it is simpler with fewer potential points of failure. Therefore, all of our swerve drive code from last year needs to be refactored into tank drive.

### CODE REVIEW

**Comment by pwmarshall** [comment]
can remove motorGet service definition from drivetrain_node as it is no longer used.
also after refactor motorSet service is not being called correctly from the drivetrain_node (line 87-90).

**Comment by Isopod00** [comment]
> can remove motorGet service definition from drivetrain_node as it is no longer used. also after refactor motorSet service is not being called correctly from the drivetrain_node (line 87-90).

Done. Thanks for catching these issues!

**Comment by Isopod00** [comment]
All tasks for this PR are completed now! Ready for review

**Review by pwmarshall — APPROVED** [review]
could update cmd_vel topic to be just a vector3 instead of a twist (could've last year) but very minor

**Comment by Isopod00** [comment]
> could update cmd_vel topic to be just a vector3 instead of a twist (could've last year) but very minor

/cmd_vel is a standard ROS thing and Twist is the standard message type for it, so we should leave it. This is the message type Nav2 uses for /cmd_vel so we want to keep it the same, it's a standard.

**Review by BergerKing333 — APPROVED** [review]
Looks good to me.

**Pull request merged**
